export default {
    cdnPrefix: 'http://demo.com',
    port: '8732',
    pacPort: '58732',
    devHost: 'demo.com',
    ethernet: 'Wi-Fi',
    mock: 'mock/index.js',
    layout: 'src/layout.js',
    dist: 'dist',
    page: 'page',
    src: 'src',
    srcPage: 'src/page',
    favicon: 'src/img/favicon.ico',
    hashPath: 'on',
    hashMap: 'dist/hash-map.json',
    webpack: 'off',
    pac: 'off',
    liveReload: 'on',
    lang: 'babel'
};
